source 'https://rubygems.org'
ruby '2.1.1'

gem 'puma'
gem 'rest_client'
gem 'scorched'
gem 'redcarpet'
gem 'slim'
gem 'coffee-script'
gem 'sprockets'
gem 'sprockets-sass'
gem 'compass'
gem 'foundation'
